#!/usr/bin/env python3
"""Train an imitation-learning policy from bot dataset CSV.

This script trains a small MLP classifier that predicts action classes:
0=up, 1=right, 2=down, 3=left.
"""

from __future__ import annotations

import argparse
import csv
import json
import random
from dataclasses import dataclass
from pathlib import Path

try:
    import torch
    from torch import nn
except ImportError as exc:  # pragma: no cover - runtime dependency check
    raise SystemExit(f"PyTorch is required for bot_train.py: {exc}") from exc


FEATURE_COLUMNS = [
    "level",
    "score",
    "body_len",
    "head_x",
    "head_y",
    "dir_x",
    "dir_y",
    "food_dx",
    "food_dy",
    "power_dx",
    "power_dy",
    "power_type",
    "power_active",
    "ghost_active",
    "shield_active",
    "portal_active",
    "laser_active",
    "danger_up",
    "danger_right",
    "danger_down",
    "danger_left",
]
LABEL_COLUMN = "action"


@dataclass
class Dataset:
    x: torch.Tensor
    y: torch.Tensor


class MlpPolicy(nn.Module):
    def __init__(self, input_dim: int) -> None:
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(input_dim, 64),
            nn.ReLU(),
            nn.Linear(64, 64),
            nn.ReLU(),
            nn.Linear(64, 4),
        )

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.net(x)


def load_csv(path: Path) -> Dataset:
    rows_x: list[list[float]] = []
    rows_y: list[int] = []
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f)
        missing = [c for c in FEATURE_COLUMNS + [LABEL_COLUMN] if c not in reader.fieldnames]
        if missing:
            raise RuntimeError(f"dataset missing required columns: {missing}")
        for row in reader:
            rows_x.append([float(row[c]) for c in FEATURE_COLUMNS])
            rows_y.append(int(row[LABEL_COLUMN]))
    if not rows_x:
        raise RuntimeError(f"empty dataset: {path}")
    x = torch.tensor(rows_x, dtype=torch.float32)
    y = torch.tensor(rows_y, dtype=torch.long)
    return Dataset(x=x, y=y)


def split_dataset(dataset: Dataset, train_ratio: float, seed: int) -> tuple[Dataset, Dataset]:
    n = dataset.x.shape[0]
    idx = list(range(n))
    random.Random(seed).shuffle(idx)
    train_n = max(1, min(n - 1, int(n * train_ratio)))
    train_idx = torch.tensor(idx[:train_n], dtype=torch.long)
    val_idx = torch.tensor(idx[train_n:], dtype=torch.long)
    return (
        Dataset(x=dataset.x[train_idx], y=dataset.y[train_idx]),
        Dataset(x=dataset.x[val_idx], y=dataset.y[val_idx]),
    )


def zscore_fit(x: torch.Tensor) -> tuple[torch.Tensor, torch.Tensor]:
    mean = x.mean(dim=0)
    std = x.std(dim=0, unbiased=False)
    std = torch.where(std < 1e-6, torch.ones_like(std), std)
    return mean, std


def zscore_apply(x: torch.Tensor, mean: torch.Tensor, std: torch.Tensor) -> torch.Tensor:
    return (x - mean) / std


def accuracy(logits: torch.Tensor, labels: torch.Tensor) -> float:
    pred = logits.argmax(dim=1)
    return float((pred == labels).float().mean().item())


def run_epoch(
    model: nn.Module,
    optimizer: torch.optim.Optimizer,
    x: torch.Tensor,
    y: torch.Tensor,
    batch_size: int,
    train: bool,
) -> tuple[float, float]:
    criterion = nn.CrossEntropyLoss()
    n = x.shape[0]
    permutation = torch.randperm(n) if train else torch.arange(n)
    total_loss = 0.0
    total_acc = 0.0
    batches = 0
    model.train(train)
    for i in range(0, n, batch_size):
        idx = permutation[i : i + batch_size]
        xb = x[idx]
        yb = y[idx]
        logits = model(xb)
        loss = criterion(logits, yb)
        if train:
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
        total_loss += float(loss.item())
        total_acc += accuracy(logits, yb)
        batches += 1
    return total_loss / max(1, batches), total_acc / max(1, batches)


def main() -> int:
    parser = argparse.ArgumentParser(description="Train MLP imitation policy from bot CSV dataset.")
    parser.add_argument("--dataset", required=True, help="CSV generated by bot dataset script")
    parser.add_argument("--output-model", required=True, help="Output .pt file")
    parser.add_argument("--output-metadata", required=True, help="Output metadata JSON")
    parser.add_argument("--epochs", type=int, default=30)
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument("--lr", type=float, default=1e-3)
    parser.add_argument("--train-ratio", type=float, default=0.9)
    parser.add_argument("--seed", type=int, default=20260304)
    args = parser.parse_args()

    random.seed(args.seed)
    torch.manual_seed(args.seed)

    dataset = load_csv(Path(args.dataset))
    train_data, val_data = split_dataset(dataset, args.train_ratio, args.seed)

    mean, std = zscore_fit(train_data.x)
    train_x = zscore_apply(train_data.x, mean, std)
    val_x = zscore_apply(val_data.x, mean, std)

    model = MlpPolicy(input_dim=train_x.shape[1])
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.lr)

    best_val_acc = -1.0
    best_state = None
    history: list[dict] = []
    for epoch in range(1, args.epochs + 1):
        train_loss, train_acc = run_epoch(
            model=model,
            optimizer=optimizer,
            x=train_x,
            y=train_data.y,
            batch_size=max(1, args.batch_size),
            train=True,
        )
        with torch.no_grad():
            val_loss, val_acc = run_epoch(
                model=model,
                optimizer=optimizer,
                x=val_x,
                y=val_data.y,
                batch_size=max(1, args.batch_size),
                train=False,
            )
        history.append(
            {
                "epoch": epoch,
                "train_loss": train_loss,
                "train_acc": train_acc,
                "val_loss": val_loss,
                "val_acc": val_acc,
            }
        )
        print(
            f"[bot-train] epoch={epoch:03d} train.loss={train_loss:.4f} train.acc={train_acc:.4f} "
            f"val.loss={val_loss:.4f} val.acc={val_acc:.4f}"
        )
        if val_acc > best_val_acc:
            best_val_acc = val_acc
            best_state = {
                "model_state_dict": model.state_dict(),
                "feature_mean": mean,
                "feature_std": std,
            }

    if best_state is None:
        raise RuntimeError("training failed to produce model state")

    output_model = Path(args.output_model).resolve()
    output_model.parent.mkdir(parents=True, exist_ok=True)
    torch.save(best_state, output_model)

    output_metadata = Path(args.output_metadata).resolve()
    output_metadata.parent.mkdir(parents=True, exist_ok=True)
    metadata = {
        "dataset": str(Path(args.dataset).resolve()),
        "model": str(output_model),
        "input_dim": len(FEATURE_COLUMNS),
        "labels": {"0": "up", "1": "right", "2": "down", "3": "left"},
        "epochs": args.epochs,
        "batch_size": args.batch_size,
        "lr": args.lr,
        "train_ratio": args.train_ratio,
        "seed": args.seed,
        "best_val_acc": best_val_acc,
        "history_tail": history[-10:],
        "feature_columns": FEATURE_COLUMNS,
    }
    output_metadata.write_text(json.dumps(metadata, indent=2) + "\n", encoding="utf-8")
    print(f"[bot-train] model={output_model}")
    print(f"[bot-train] metadata={output_metadata}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
